# 서버포트
server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# gRPC 서버포트
grpc:
  server:
    port: 50051 # gRPC 서버 포트
    maxInboundMessageSize: 10485760 # 최대 메시지 크기 (10MB)grpc:

jwt:
  secret-key: "your-256-bit-secret-key-base64-encoded"